"""Initialize the character sheet here and import for use"""

character_sheet = {
    "class": [None],
    "level": [0],
    "race": None,
    "alignment": None,
    "experience": None,
    "stats": {
        "strength": 0,
        "dexterity": 0,
        "constitution": 0,
        "intelligence": 0,
        "wisdom": 0,
        "charisma": 0
    },
    "proficiency bonus": 0,
    "saving throws": {
        "strength": 0,
        "dexterity": 0,
        "constitution": 0,
        "intelligence": 0,
        "wisdom": 0,
        "charisma": 0
    },
    "skills": {
        "acrobatics": 0,
        "animal handling": 0,
        "arcana": 0,
        "athletics": 0,
        "deception": 0,
        "history": 0,
        "insight": 0,
        "intimidation": 0,
        "investigation": 0,
        "medicine": 0,
        "nature": 0,
        "perception": 0,
        "performance": 0,
        "persuasion": 0,
        "religion": 0,
        "sleight of hand": 0,
        "stealth": 0,
        "survival": 0
    },
    "passive perception": 0,
    "armor class": 0,
    "initiative": 0,
    "speed": 0,
    "hit points": 0,
    "hit dice": 0,
    "personality traits": None,
    "ideals": None,
    "bonds": None,
    "flaws": None,
    "attacks": None,
    "prepared spells": None,
    "languages": None,
    "other proficiencies": [None],
    "equipment": [None],
    "traits": [None],
    "feats": [None],
    "age": 0,
    "height": 0,
    "weight": 0,
    "eye color": None,
    "skin color": None,
    "hair color": None,
    "allies": [None],
    "organizations": [None],
    "treasure": [None],
    "spellcasting class": None,
    "spellcasting ability": None,
    "spell save dc": 0,
    "spell attack bonus": 0,
    "known spells": {
        "level 0 cantrips": {None},
        "level 1 spells": {None},
        "level 2 spells": {None},
        "level 3 spells": {None},
        "level 4 spells": {None},
        "level 5 spells": {None},
        "level 6 spells": {None},
        "level 7 spells": {None},
        "level 8 spells": {None},
        "level 9 spells": {None},
    }
}